<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SelfContained>false</SelfContained>
    <PublishAot>false</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../FfmpegBackend.cs" Link="FfmpegBackend.cs" />
    <PackageReference Include="FFmpeg.AutoGen" Version="8.0.0" />
  </ItemGroup>
</Project>
