$ErrorActionPreference = 'Stop'
$projectRoot = $PSScriptRoot
$demoDirectory = Join-Path $projectRoot 'demo'
[IO.Directory]::CreateDirectory($demoDirectory) | Out-Null
$imports = [Collections.Generic.SortedSet[string]]::new([StringComparer]::Ordinal)
$bodies = [Collections.Generic.List[string]]::new()
foreach ($sourceFile in Get-ChildItem -LiteralPath $projectRoot -Filter 'Ffmpeg*.cs' | Sort-Object Name) {
    $body = [Collections.Generic.List[string]]::new()
    foreach ($line in [IO.File]::ReadAllLines($sourceFile.FullName)) {
        if ($line -match '^using .+;$') { [void]$imports.Add($line) }
        elseif ($line -ne 'namespace Frd;') { $body.Add($line) }
    }
    $bodies.Add('// Source: ' + $sourceFile.Name + [Environment]::NewLine + ($body -join [Environment]::NewLine).Trim())
}
$combined = '// Generated by Build-SingleFileDemo.ps1 from the tested production sources.' + [Environment]::NewLine +
    ($imports -join [Environment]::NewLine) + [Environment]::NewLine + [Environment]::NewLine +
    'namespace Frd;' + [Environment]::NewLine + [Environment]::NewLine +
    ($bodies -join ([Environment]::NewLine + [Environment]::NewLine)) + [Environment]::NewLine
[IO.File]::WriteAllText((Join-Path $demoDirectory 'FrdDemo.cs'), $combined)
Copy-Item -LiteralPath (Join-Path $projectRoot 'codec-config.json') -Destination (Join-Path $demoDirectory 'codec-config.json')
Write-Output ('Generated ' + (Join-Path $demoDirectory 'FrdDemo.cs'))
