<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>../app.manifest</ApplicationManifest>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <StartupObject>Frd.Program</StartupObject>
    <Version>2.0.0-pre1</Version>
    <InformationalVersion>v2.pre1</InformationalVersion>
    <SelfContained>false</SelfContained>
    <PublishAot>false</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="8.0.0" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="12.1.1" />
    <Compile Include="FrdDemo.cs" />
    <Content Include="codec-config.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../third_party/ffmpeg/runtime/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" ExcludeFromSingleFile="true" TargetPath="ffmpeg/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
